// Generated by CoffeeScript 1.10.0
(function() {
  window.logMe = function(severity, message, data) {
    var params, r, url;
    params = Object.extend({
      Source: 'BigBrainz',
      Severity: severity,
      Platform: 'WebGLPage',
      Message: '[' + severity + ']' + message,
      BBSessionID: window.sessionID,
      TimeStamp: new Date().toISOString()
    }, data);
    url = 'https://Testlogger.my.imaginelearning.com/v1.0/logs';
    r = new XMLHttpRequest();
    r.open("POST", url, true);
    r.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    r.onreadystatechange = function() {
      if (r.readyState !== 4 || r.status !== 200) {

      }
    };
    return r.send(JSON.stringify(params));
  };

  window.logMeJSON = function(severity, message, data) {
    return logMe(severity, message, JSON.parse(data));
  };

}).call(this);

//# sourceMappingURL=logger.js.map
